config/routes.rb
Rails.application.routes.draw do
  resources :pacings
  root 'run_logs#index'
  resources :run_logs
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pacing.rb
class Pacing < ApplicationRecord
  belongs_to :user
  belongs_to :run_log
end

app/models/run_log.rb
class RunLog < ApplicationRecord
  belongs_to :user
  has_many :pacings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :run_log
  has_many :pacings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pacings_controller.rb
class PacingsController < ApplicationController
  before_action :set_pacing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  # GET /pacings
  # GET /pacings.json
  def index
    @pacings = Pacing.where(run_log_id: (params[:run_log_id]),user_id: current_user.id)
  end

  # GET /pacings/1
  # GET /pacings/1.json
  def show
  end

  # GET /pacings/new
  def new
    @pacing = Pacing.new

  end

  # GET /pacings/1/edit
  def edit
  end

  # POST /pacings
  # POST /pacings.json
  def create
    @pacing = Pacing.new(pacing_params)
    @pacing.user = current_user

    respond_to do |format|
      if @pacing.save
        format.html { redirect_to @pacing, notice: 'Pacing was successfully created.' }
        format.json { render :show, status: :created, location: @pacing }
        return
      else
        byebug
        format.html { render :new }
        format.json { render json: @pacing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacings/1
  # PATCH/PUT /pacings/1.json
  def update
    respond_to do |format|
      if @pacing.update(pacing_params)
        format.html { redirect_to @pacing, notice: 'Pacing was successfully updated.' }
        format.json { render :show, status: :ok, location: @pacing }
        return
      else
        format.html { render :edit }
        format.json { render json: @pacing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacings/1
  # DELETE /pacings/1.json
  def destroy
    @pacing.destroy
    respond_to do |format|
      format.html { redirect_to pacings_url, notice: 'Pacing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pacing
      @pacing = Pacing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pacing_params
      params.require(:pacing).permit(:body, :run_log_id)
    end
end

app/controllers/run_logs_controller.rb
class RunLogsController < ApplicationController
  before_action :set_run_log, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  # GET /run_logs
  # GET /run_logs.json
  def index
    @run_logs = RunLog.where(user_id: (current_user.id))
  end

  # GET /run_logs/1
  # GET /run_logs/1.json
  def show
  end

  # GET /run_logs/new
  def new
    @run_log = RunLog.new
  end

  # GET /run_logs/1/edit
  def edit
  end

  # POST /run_logs
  # POST /run_logs.json
  def create
    @run_log = RunLog.new(run_log_params)
    @run_log.user = current_user

    respond_to do |format|
      if @run_log.save
        format.html { redirect_to @run_log, notice: 'Run log was successfully created.' }
        format.json { render :show, status: :created, location: @run_log }
        return
      else
        format.html { render :new }
        format.json { render json: @run_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /run_logs/1
  # PATCH/PUT /run_logs/1.json
  def update
    respond_to do |format|
      if @run_log.update(run_log_params)
        format.html { redirect_to @run_log, notice: 'Run log was successfully updated.' }
        format.json { render :show, status: :ok, location: @run_log }
      else
        format.html { render :edit }
        format.json { render json: @run_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /run_logs/1
  # DELETE /run_logs/1.json
  def destroy
    @run_log.destroy
    respond_to do |format|
      format.html { redirect_to run_logs_url, notice: 'Run log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run_log
      @run_log = RunLog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def run_log_params
      params.require(:run_log).permit(:distance, :time, :pace)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pacings_helper.rb
module PacingsHelper
end

app/helpers/run_logs_helper.rb
module RunLogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RunTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pacings/_form.html.erb
<%= form_with(model: pacing, local: true) do |form| %>
  <% if pacing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pacing.errors.count, "error") %> prohibited this pacing from being saved:</h2>

      <ul>
        <% pacing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :run_logs_id %>
    <%= form.text_field :run_logs_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pacings/edit.html.erb
<h1>Editing Pacing</h1>

<%= render 'form', pacing: @pacing %>

<%= link_to 'Show', @pacing %> |
<%= link_to 'Back', pacings_path %>

app/views/pacings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pacings</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Run logs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacings.each do |pacing| %>
      <tr>
        <td><%= pacing.body %></td>
        <td><%= pacing.user_id %></td>
        <td><%= pacing.run_logs_id %></td>
        <td><%= link_to 'Show', pacing %></td>
        <td><%= link_to 'Edit', edit_pacing_path(pacing) %></td>
        <td><%= link_to 'Destroy', pacing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pacing', new_pacing_path %>

app/views/pacings/new.html.erb
<h1>New Pacing</h1>

<%= render 'form', pacing: @pacing %>

<%= link_to 'Back', pacings_path %>

app/views/pacings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @pacing.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @pacing.user_id %>
</p>

<p>
  <strong>Run logs:</strong>
  <%= @pacing.run_logs_id %>
</p>

<%= link_to 'Edit', edit_pacing_path(@pacing) %> |
<%= link_to 'Back', pacings_path %>

app/views/run_logs/_form.html.erb
<%= form_with(model: run_log, local: true) do |form| %>
  <% if run_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(run_log.errors.count, "error") %> prohibited this run_log from being saved:</h2>

      <ul>
        <% run_log.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :distance %>
    <%= form.text_field :distance %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/run_logs/edit.html.erb
<h1>Editing Run Log</h1>

<%= render 'form', run_log: @run_log %>

<%= link_to 'Show', @run_log %> |
<%= link_to 'Back', run_logs_path %>

app/views/run_logs/index.html.erb
<!-- login/logout -->
<% if user_signed_in? %>
	<!-- first subheader -->
	<div class="divider"></div>
    <%= link_to 'Log out', destroy_user_session_url, method: :delete %>

<% else %>
  <!-- first subheader -->
 <div class="divider"></div>
 <a class="subheader">Login/sign up</a>
<%= link_to 'Log in', new_user_session_url, :class => "waves-effect" %>
<%= link_to "Sign up", new_user_registration_path, :class => "waves-effect" %>
<% end %>
<%= javascript_pack_tag 'hello_react' %>
<%= stylesheet_pack_tag 'hello_react' %>

app/views/run_logs/new.html.erb
<h1>New Run Log</h1>

<%= render 'form', run_log: @run_log %>

<%= link_to 'Back', run_logs_path %>

app/views/run_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Distance:</strong>
  <%= @run_log.distance %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @run_log.time %>
</p>

<p>
  <strong>User:</strong>
  <%= @run_log.user_id %>
</p>

<%= link_to 'Edit', edit_run_log_path(@run_log) %> |
<%= link_to 'Back', run_logs_path %>